# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hanhuoer
subtitle: 分享技术，品味人生
name: Hanhuoer
email: hanhuoer@126.com
description: Java
keywords: Hanhuoer,Java,后端,程序员,程序猿
encoding: "utf-8"
favicon: favicon.ico

repository: hanhuoer/hanhuoer.github.io
github_url: https://github.com/hanhuoer
url: http://hanhuoer.github.io
enforce_ssl: hanhuoer.github.io

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
  coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
menus:

  - href: /link.html
    label: 友链
    target: _self


# Navigation. main menu list
navs:

  - href: /
    label: Home

  - href: /spring-boot.html
    label: Spring Boot
    target: _self
    subnav:

  - href: /spring-cloud.html
    label: Spring Cloud
    target: _self

  - href: /java.html
    label: Java
    target: _self
    subnav:

  - href: /archives.html
    label: Archives
    target: _self

  - href: /about.html
    label: About
    target: _self


# labels. my blog key words
labels:

  - href: /payment.html
    label: 支付
    target: _self

  - href: /fastdfs.html
    label: FastDFS
    target: _blank


# selected articles
classes:

  #  - href: /life.html
  #    name: 我的故事
  #    describe: 生活就是故事，故事就是生活

  - href: /payment.html
    name: 支付系列
    describe: 支付，第三方支付


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitment
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
  username: hanhuoer
# https://imsun.net/posts/gitment-introduction/
gitment:
  owner: hanhuoer
  repo: blog-comments
  oauth:
    client_id: b108dd64f80ec990f9f2
    client_secret: b181739ce5b5fc5ff94ec023fb4c0e85078fc863
# https://github.com/gitalk/gitalk#install
gitalk:
  owner: hanhuoer
  repo: blog-comments
  clientID: b108dd64f80ec990f9f2
  clientSecret: b181739ce5b5fc5ff94ec023fb4c0e85078fc863
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus: true
